# Perfil de producción — sobrescribe application.properties
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.com.tfg.api=WARN
logging.level.org.springframework.security=WARN
logging.level.org.flywaydb=WARN
